name = "LLMRateLimiters"
uuid = "ed1ca689-44f5-49fd-ae5c-d523230a773a"
authors = ["SixZero <havliktomi@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PromptingTools = "670122d1-24a8-4d70-bfce-740807c42192"

[compat]
Aqua = "0.8.9"
Dates = "1.11.0"
HTTP = "1.10"
InteractiveUtils = "1.11.0"
JSON3 = "1.14.1"
PrecompileTools = "1.2.1"
PromptingTools = "â‰¥ 0.65"
Test = "<0.0.1, 1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[targets]
test = ["Aqua", "Test", "InteractiveUtils"]
